# SPDX-FileCopyrightText: 2025 reactor_file contributors <https://github.com/ash-project/reactor_file/graphs/contributors>
#
# SPDX-License-Identifier: MIT

---
updates:
  - directory: /
    groups:
      dev-dependencies:
        dependency-type: development
      production-dependencies:
        dependency-type: production
    package-ecosystem: mix
    schedule:
      interval: monthly
    versioning-strategy: lockfile-only
version: 2
